apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nodupdate-job
spec:
  schedule: "0 */8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 5
          volumes:
            - name: nod-pv-storage
              persistentVolumeClaim:
                claimName: nod-pv-claim
            - name: license-file
              configMap:
                name: nodlicense-config
          containers:
            - name: nod-pv-container
              image: gmska2011/nodupdate:latest
              volumeMounts:
                - mountPath: "/app/nod"
                  name: nod-pv-storage
                - name: license-file
                  mountPath: /app/license/mirror.lf
                  subPath: mirror.lf


