---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nod-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/nodupdate/nod/"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nod-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
