apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30036
  selector:
    app: nginx